config/routes.rb
Rails.application.routes.draw do
  get 'orders/create'

  get 'carts/show'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  devise_for :users
  root                      'static_pages#home'
  get 'settings',           to: 'static_pages#settings'
  get 'blog/',              to: 'markdown_blog#index'
  get 'blog/*path',         to: 'markdown_blog#show'
  resources :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  validates :product_id,  presence: true,
                          numericality: { only_integer: true,
                                          greater_than_or_equal_to: 0 }
  validates :order_id,    presence: true,
                          numericality: { only_integer: true,
                                          greater_than_or_equal_to: 0 }
  validates :quantity,    presence: true,
                          numericality: { only_integer: true,
                                          greater_than_or_equal_to: 0 }
  validates :price,       presence: true,
                          numericality: { only_integer: true,
                                          greater_than_or_equal_to: 0 }
  validates :total,       presence: true,
                          numericality: { only_integer: true,
                                          greater_than_or_equal_to: 0 }
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items
  validates :name, presence: true
  validates :quantity,  presence: true,
                        numericality: { only_integer: true,
                                        greater_than_or_equal_to: 0 }
  validates :price,     presence: true,
                        numericality: { greater_than_or_equal_to: 0 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end
end

app/controllers/markdown_blog_controller.rb
class MarkdownBlogController < ApplicationController
  include MarkdownBlogHelper
  attr_reader :content

  def index
    posts = Dir.glob("public/*/*/*.md")
    @content = Array.new
    posts.each do |post|
      title, slug_final = get_slug_final(post)
      # first line will be an image
      first_line = File.foreach(post).first(1)
      # change the CSS class for the blog index page
      first_line = first_line.join("").to_s.gsub(/col-md-offset-3 blog-main-img/, 'blog-excerpt-img')
      next if first_line.match(/^draft/)
      # only using the image as an excerpt
      excerpt = md_to_html(first_line)
      @content << [title, slug_final, excerpt]
    end
  end

  def show
    file_path = "#{Rails.root}/" + params[:path] + ".md"
    md_content = File.read(file_path)
    @content = md_to_html(md_content)
  end

  private

    # get the title and slug. note that the slug is not actually modified here
    # and only the title field is currently used, but other fields are available.
    def get_slug_final(slug)
      slug_fields = []
      slug_fields = slug.match(/(\w+?\/)(\w+?)\/(\d{4})\/(\S+?\.md)/)
      category = slug_fields[2]
      year = slug_fields[3]
      file_name = slug_fields[4]
      title = file_name.split(/-/).map(&:capitalize).join(' ').gsub(/\.md$/, '')
      slug_final = "public/#{category}/#{year}/#{file_name}"
      return title, slug_final
    end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    if current_user.order.id
      @order_item = OrderItem.new()
  end

  def update
  end

  def destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @order = Order.new(user_id: current_user.id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:settings]

  def home
  end

  def settings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/markdown_blog_helper.rb
module MarkdownBlogHelper
  def md_to_html(text)
    options = {
      filter_html:     false,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true,
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true,
      no_intra_emphasis:  true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Lovacitta Naturals</small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <nav>
      <ul class="nav navbar-nav navbar-inverse navbar-logo">
        <div id="logo">
          <%= image_tag("/assets/logo.png", size: "350x45", alt: "Lovacitta Naturals") %>
        </div>
        <% if user_signed_in? %>
          <li><%= link_to '#', class: "btn btn-default btn-no-border"  do %>
              <span class="glyphicon glyphicon-shopping-cart"></span>
            <% end %>
          </li>
          <li class="dropdown">
            <a href='#' class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-cog"></span><b class="caret"></b>
            </a>
            <ul class="dropdown-menu dropdown-bg pull-right">
              <li><%= link_to "Settings", settings_path %></li>
              <li><%= link_to "Edit profile", edit_user_registration_path %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to '#', class: "btn btn-default btn-no-border"  do %>
              <span class="glyphicon glyphicon-shopping-cart"></span>
            <% end %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-inverse navbar-main">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Shop", products_path %></li>
        <li><%= link_to "Blog", blog_path %></li>
      </ul>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Lovacitta Naturals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <% unless notice.nil? %>
      <p class="notice alert alert-warning"><%= notice %></p>
    <% end %>
    <% unless alert.nil? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/markdown_blog/index.html.erb
<h1>Blog</h1>

<% @content.each do |title, slug, excerpt| %>
  <div class="row blog-excerpt">
    <div class="col-md-2 col-md-offset-4">
      <h2 class="blog-excerpt-title"><%= link_to title, controller: "markdown_blog", action: "show", path: slug %></h2>
    </div>
    <div class="col-md-6">
      <%= excerpt %>
      <p><small><%= link_to "Read more >", controller: "markdown_blog", action: "show", path: slug %></small></p>
    </div>
  </div>
<% end %>

app/views/markdown_blog/show.html.erb
<div class="article">
  <%= @content %>
</div>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Shop</h1>
<% @products.each_slice(3) do |products| %>
  <div class="row">
    <% products.each do |product| %>
      <div class="col-md-3 products">
        <%= link_to product.name, product_path(product.id) %><br>
        <%= product.description %><br>
        <%= product.price %><br>
      </div>
    <% end %>
  </div>
<% end %>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-3 product">
    <strong><%= @product.name %></strong><br>
    <%= @product.description %><br>
    <%= @product.price %><br>
    <%= link_to "Add to Cart", '#' %>
  </div>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/static_pages/home.html.erb
<div class="row banner">
  <%= image_tag("/assets/coconut-skyline.jpg", alt: "coconut tree skyline") %>
</div>

<p><strong>Welcome to Lovacitta Naturals</strong></p>

app/views/static_pages/settings.html.erb
<h1>Settings</h1>

<% if user_signed_in? %>
  <%= current_user.email %>
<% else %>
  <%= redirect_to root_url %>
<% end %>